name: Build platforms

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.4.3'
          host: 'windows'
          target: 'desktop'
          arch: 'win64_mingw'
          dir: '${{ github.workspace }}/'
          install-deps: 'true'
          cache: 'false'
          cache-key-prefix: 'install-qt-action'
          setup-python: 'true'
          tools: 'tools_cmake tools_mingw,qt.tools.win64_mingw810 tools_ninja'
          archives: 'qttools qtbase MinGW'
          set-env: 'true'
          tools-only: 'false'
          aqtversion: '==3.1.*'
          py7zrversion: '==0.20.*'
          extra: '--external 7z'
      - name: Build
        shell: cmd
        run: |
          dir
          mkdir build
          cd build
          cmake ..
          cd ..
          cmake --build build
