name: Build platforms

on:
  push:
    branches:
      - main
      
env:
  VERSION_NUMBER: 0.5
  QT_VERSION: 6.3.1
  PROJECT: "LetItOut"
  

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '${{ env.QT_VERSION }}'
          host: 'windows'
          target: 'desktop'
          arch: 'win64_msvc2019_64'
          dir: '${{ github.workspace }}/'
          install-deps: 'true'
          cache: 'true'
          cache-key-prefix: 'install-qt-action'
          setup-python: 'true'
          tools: 'tools_cmake tools_vcredist,qt.tools.vcredist_msvc2019_x64 tools_ninja'
          archives: 'qttools qtbase MinGW'
          set-env: 'true'
          tools-only: 'false'
          aqtversion: '==3.1.*'
          py7zrversion: '==0.20.*'
          extra: '--external 7z'
      - name: Build
        shell: cmd
        run: |
          dir
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release ..
          cmake --build .
      - name: Deploy
        shell: cmd
        run: |
          "Qt\${{ env.QT_VERSION }}\msvc2019_64\bin\windeployqt.exe" build/Debug/${{ env.PROJECT }}.exe
          dir "build\Debug"
  build-linux:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '${{ env.QT_VERSION }}'
          host: 'linux'
          target: 'desktop'
          arch: 'gcc_64'
          dir: '${{ github.workspace }}/'
          install-deps: 'true'
          cache: 'true'
          cache-key-prefix: 'install-qt-action'
          setup-python: 'true'
          tools: 'tools_cmake tools_ninja'
          set-env: 'true'
          tools-only: 'false'
          aqtversion: '==3.1.*'
          py7zrversion: '==0.20.*'
          extra: '--external 7z'
      - name: Install LinuxDeploy
        uses: miurahr/install-linuxdeploy-action@v1
        with:
          plugins: qt appimage
      - name: Build
        shell: sh
        run: |
          dir
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release ..
          cmake --build .
      - name: Deploy
        shell: sh
        run: |
          linuxdeploy-x86_64.AppImage --appdir build --plugin=qt --output=appimage
          ls build
      - name: Archive Linux binaries
        uses: actions/upload-artifact@v2
        with:
          name: linux-binaries
          path: "./build"
